### ISSUE TITLE
Exiting search is not working fine I think

### ISSUE THREAD

**Issue by Piripe** [yasandev/yasan-launcher-issues#22]
**Describe the bug**
When I try to exit the search it didn't exit sometimes

**To Reproduce**
1. Open the search
2. Quit the search

**Expected behavior**
I want to exit the search when I use the button to exit the search

**Screenshots**

https://user-images.githubusercontent.com/77517308/156582243-f1747d59-0f60-49fe-a751-fb8d4497e341.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox (The best browser)
 - Version: 21H2

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Android 11 (With Oxygen OS 11.1.8.8.AC01DA)
 - Browser Firefox (The best browser)
 - Version 22.01

**Additional context**
In the video I used the back gesture but I've the same problem with the back search button

**Comment by yasanglass** [comment]
The back interaction on Search is a bit weird sometimes but I think it is fixed on the DEV variant. On the latest DEV version, the search is moved to the top due to some issues related to Compose (UI toolkit the app is created with) which appears to also have fixed this issue. If you could check the DEV version and report it would be great. 

The DEV changes will come to stability in a day or two as well.

**Comment by yasanglass** [comment]
YASAN Launcher 22.03 is now released and should fix this issue. I'm closing this issue but please check and report if it still isn't fixed for you.
