### ISSUE TITLE
Sometimes the search is not opening fine (I think)

### ISSUE THREAD

**Issue by Piripe** [yasandev/yasan-launcher-issues#23]
**Describe the bug**
Randomly sometimes the search is opening behind the keyboard

**To Reproduce**
1. Open the search

**Expected behavior**
Open correctly the search every time

**Screenshots**

https://user-images.githubusercontent.com/77517308/156583508-9009d3d0-b2c5-457f-b103-07fba5347578.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox (The best browser)
 - Version: 21H2

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Android 11 (With Oxygen OS 11.1.8.8.AC01DA)
 - Browser Firefox (The best browser)
 - Version 22.01

**Additional context**
In the video I used the back gesture but I've the same problem with the back search button

**Comment by yasanglass** [comment]
This is a Compose bug. You can track it here:
https://issuetracker.google.com/issues/190539358

Basically, I have reported it months ago but they haven't been able to really fix it yet. Due to that, I have moved the search text field to the top on the latest DEV versions which will be merged into the stable branch in a day or two.

**Comment by yasanglass** [comment]
YASAN Launcher 22.03 is now released and should fix this issue. I'm closing this issue but please check and report if it still isn't fixed for you.
